
import type { Trainer, FitnessClass, MembershipPlan } from './types';
import { Zap, ShieldCheck, Star, Dumbbell, Users, Activity } from 'lucide-react';

export const trainers: Trainer[] = [
  {
    id: '1',
    name: 'Alex Morgan',
    bio: 'Certified personal trainer with 10 years of experience in strength training and HIIT. Passionate about helping clients achieve their peak fitness.',
    specializations: ['Strength Training', 'HIIT', 'Functional Fitness'],
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: '2',
    name: 'Sam Kerr',
    bio: 'Yoga Alliance certified instructor focusing on Vinyasa and restorative yoga. Believes in the mind-body connection for overall wellness.',
    specializations: ['Vinyasa Yoga', 'Restorative Yoga', 'Meditation'],
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: '3',
    name: 'Chris Bumstead',
    bio: 'Former athlete turned Pilates and Cardio expert. Chris brings high energy and motivation to every class.',
    specializations: ['Pilates', 'Cardio Blast', 'Core Strength'],
    imageUrl: 'https://placehold.co/300x300.png',
  },
];

export const fitnessClasses: FitnessClass[] = [
  {
    id: 'c1',
    name: 'Morning Yoga Flow',
    trainerId: '2',
    trainerName: 'Sam Kerr',
    day: 'Monday',
    time: '07:00 AM',
    duration: '60 minutes',
    spotsAvailable: 15,
    type: 'Yoga',
  },
  {
    id: 'c2',
    name: 'HIIT Power Hour',
    trainerId: '1',
    trainerName: 'Alex Morgan',
    day: 'Monday',
    time: '06:00 PM',
    duration: '60 minutes',
    spotsAvailable: 10,
    type: 'HIIT',
  },
  {
    id: 'c3',
    name: 'Strength Foundations',
    trainerId: '1',
    trainerName: 'Alex Morgan',
    day: 'Tuesday',
    time: '05:00 PM',
    duration: '75 minutes',
    spotsAvailable: 8,
    type: 'Strength',
  },
  {
    id: 'c4',
    name: 'Cardio Kickstart',
    trainerId: '3',
    trainerName: 'Chris Bumstead',
    day: 'Wednesday',
    time: '08:00 AM',
    duration: '45 minutes',
    spotsAvailable: 20,
    type: 'Cardio',
  },
  {
    id: 'c5',
    name: 'Pilates Core Fusion',
    trainerId: '3',
    trainerName: 'Chris Bumstead',
    day: 'Thursday',
    time: '06:30 PM',
    duration: '60 minutes',
    spotsAvailable: 12,
    type: 'Pilates',
  },
  {
    id: 'c6',
    name: 'Evening Restorative Yoga',
    trainerId: '2',
    trainerName: 'Sam Kerr',
    day: 'Friday',
    time: '07:00 PM',
    duration: '60 minutes',
    spotsAvailable: 15,
    type: 'Yoga',
  },
  {
    id: 'c7',
    name: 'Full Body Blast (HIIT)',
    trainerId: '1',
    trainerName: 'Alex Morgan',
    day: 'Saturday',
    time: '10:00 AM',
    duration: '60 minutes',
    spotsAvailable: 10,
    type: 'HIIT',
  },
];

export const membershipPlans: MembershipPlan[] = [
  {
    id: 'plan-basic',
    name: 'Basic Fit',
    price: '$29',
    priceFrequency: 'per month',
    description: 'Perfect for getting started and regular gym access.',
    features: [
      'Full Gym Access',
      'Cardio & Strength Zones',
      'Locker Rooms & Showers',
      'Online Progress Tracking',
    ],
    ctaText: 'Get Started',
    icon: Dumbbell,
  },
  {
    id: 'plan-plus',
    name: 'Plus Wellness',
    price: '$49',
    priceFrequency: 'per month',
    description: 'Includes group classes and more flexibility.',
    features: [
      'All Basic Fit Features',
      'Unlimited Group Classes (Yoga, HIIT, etc.)',
      'Guest Passes (2/month)',
      'Nutritional Guidance Basics',
    ],
    ctaText: 'Choose Plus',
    isPopular: true,
    icon: Users,
  },
  {
    id: 'plan-pro',
    name: 'Pro Athlete',
    price: '$79',
    priceFrequency: 'per month',
    description: 'The ultimate package for dedicated fitness enthusiasts.',
    features: [
      'All Plus Wellness Features',
      '2 Personal Training Sessions/Month',
      'Advanced Workout Analytics',
      'Exclusive Workshops Access',
      'SR Fitness Merch Discount',
    ],
    ctaText: 'Go Pro',
    icon: Activity,
  },
];
