

import type { Product } from './types';

export const placeholderProducts: Product[] = [
    {
      id: 'prod1',
      name: 'SR Fitness Long sleeve',
      category: 'Apparel',
      price: 15000,
      image: '/longsl.jpeg',
      dataAiHint: 'fitness shirt',
      rating: 5,
      isNew: true,
      timestamp: new Date('2024-07-20T10:00:00Z').getTime(),
      sizes: ['Large', '2XL', '3XL'],
    },
    {
      id: 'prod9',
      name: 'SR Fitness Sleevles',
      category: 'Apparel',
      price: 10000,
      image: '/sleevles.jpeg',
      dataAiHint: 'fitness hoodie',
      rating: 5,
      isNew: true,
      timestamp: new Date('2024-07-25T10:00:00Z').getTime(),
      sizes: ['Large', '2XL', '3XL'],
    },
    {
      id: 'prod10',
      name: 'Short sleeve',
      category: 'Apparel',
      price: 10000,
      image: '/shortsl.jpeg',
      dataAiHint: 'tech shirt running',
      rating: 4,
      isNew: true,
      timestamp: new Date('2024-07-25T09:00:00Z').getTime(),
      sizes: ['Large', '2XL', '3XL'],
    },
    {
      id: 'prod8',
      name: 'Micronised Creatine',
      category: 'Supplements',
      price: 67500,
      image: '/cray.jpeg',
      dataAiHint: 'supplement tub',
      rating: 4,
      isNew: true,
      timestamp: new Date('2024-07-10T10:00:00Z').getTime(),
    },
    {
      id: 'prod9',
      name: 'Body Fotress',
      category: 'Supplements',
      price: 119500,
      image: '/fort.jpeg',
      dataAiHint: 'supplement tub',
      rating: 4,
      isNew: true,
      timestamp: new Date('2024-07-10T10:00:00Z').getTime(),
    },
];
