
import type { Product } from './types';

export const placeholderProducts: Product[] = [
    {
      id: 'prod1',
      name: 'SR Fitness Performance Tee',
      category: 'Apparel',
      price: 25.00,
      image: 'https://picsum.photos/seed/mp1/600/600',
      dataAiHint: 'fitness shirt',
      rating: 5,
      isNew: true,
      timestamp: new Date('2024-07-20T10:00:00Z').getTime(),
    },
    {
      id: 'prod2',
      name: 'Pro-Grip Dumbbell Set',
      category: 'Equipment',
      price: 150.00,
      image: 'https://picsum.photos/seed/mp2/600/600',
      dataAiHint: 'dumbbell set',
      rating: 5,
      isNew: false,
      timestamp: new Date('2024-07-15T10:00:00Z').getTime(),
    },
    {
      id: 'prod3',
      name: 'Flex-Fit Yoga Mat',
      category: 'Accessories',
      price: 35.00,
      image: 'https://picsum.photos/seed/mp3/600/600',
      dataAiHint: 'yoga mat',
      rating: 4,
      isNew: false,
      timestamp: new Date('2024-07-18T10:00:00Z').getTime(),
    },
    {
      id: 'prod4',
      name: 'SR-21 Whey Protein',
      category: 'Supplements',
      price: 49.99,
      image: 'https://picsum.photos/seed/mp4/600/600',
      dataAiHint: 'protein powder',
      rating: 5,
      isNew: true,
      timestamp: new Date('2024-07-21T10:00:00Z').getTime(),
    },
    {
      id: 'prod5',
      name: 'Women\'s Motion Leggings',
      category: 'Apparel',
      price: 65.00,
      image: 'https://picsum.photos/seed/mp5/600/600',
      dataAiHint: 'fitness leggings',
      rating: 5,
      isNew: false,
      timestamp: new Date('2024-07-19T10:00:00Z').getTime(),
    },
    {
      id: 'prod6',
      name: 'Adjustable Kettlebell',
      category: 'Equipment',
      price: 89.99,
      image: 'https://picsum.photos/seed/mp6/600/600',
      dataAiHint: 'kettlebell weight',
      rating: 4,
      isNew: false,
      timestamp: new Date('2024-07-12T10:00:00Z').getTime(),
    },
    {
      id: 'prod7',
      name: 'Hydro-Flow Water Bottle',
      category: 'Accessories',
      price: 19.99,
      image: 'https://picsum.photos/seed/mp7/600/600',
      dataAiHint: 'water bottle',
      rating: 5,
      isNew: true,
      timestamp: new Date('2024-07-22T10:00:00Z').getTime(),
    },
    {
      id: 'prod8',
      name: 'SR-VIVE Creatine',
      category: 'Supplements',
      price: 29.99,
      image: 'https://picsum.photos/seed/mp8/600/600',
      dataAiHint: 'supplement tub',
      rating: 4,
      isNew: false,
      timestamp: new Date('2024-07-10T10:00:00Z').getTime(),
    },
];
